# Generated by Django 5.1.2 on 2024-11-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emp_id', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('date_joined', models.DateField()),
                ('address', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('company_location', models.CharField(default='Hyderabad', max_length=50)),
                ('qualification', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
